### PR TITLE
little clean up

### PR DESCRIPTION
**Pull request by 1C0D**
not using rollup anymore. main.ts in src with directly the code in 
and some little modifications around the button

### CODE REVIEW

**Comment by 1C0D** [comment]
if you want test it on my repo https://github.com/1C0D/reveal-active-file-button-plugin?organization=1C0D&organization=1C0D

**Comment by claremacrae** [comment]
Hello,  thank you for offering some improvements.

Before investigating whether to merge this, I would need to understand the intention of the changes. 

So please kindly explain exactly what the diffs are that you made to the `.ts` code. 

Normally I would expect to be able to review the differences for myself in the GitHub website, but because you copied the file(s) then deleted, there is no meaningful history here to read.

**Comment by 1C0D** [comment]
1)  
private getFileExplorers(): WorkspaceLeaf {
   return this.app.workspace.getLeavesOfType("file-explorer")[0];
}   
// only 1 explorer is possible so no need for a loop behind  
const explorer = this.getFileExplorers();
this.addRevealButton(explorer);
         
2)
same as did before but using the function API "createEl"
	const newIcon = navContainer.createEl(
			"button",
			{
				cls: "clickable-icon nav-action-button reveal-active-file-button",
			},
			(el) => {
				el.innerHTML = REVEAL_ACTIVE_FILE_BUTTON_ICON;
			}
		);
innerHTML is passed through a callback
attributes were removed because unnecessary

**Comment by 1C0D** [comment]
my bad attribute was needed for the tip. 
then we have
```
const newIcon = navContainer.createEl(
	'button',
	{
		attr: { 'aria-label': 'Reveal active file' },
		cls: 'clickable-icon nav-action-button reveal-active-file-button'
	},
	(el) => {
		el.innerHTML = REVEAL_ACTIVE_FILE_BUTTON_ICON;
	}
);
```

**Comment by 1C0D** [comment]
I was reading the script again, and I saw you were using a timer but the command is asynchrone
so I modified the call to use it as an async func and not have to use a timer
```
private onButtonClick = (explorer: WorkspaceLeaf) => {
	if (explorer) {
		// @ts-ignore
		await this.app.commands.executeCommandById(
			'file-explorer:reveal-active-file'
		);
		}
	}
```
and then 
```
this.registerDomEvent(newIcon, 'click', async () => {
	this.onButtonClick(explorer);
});
```

**Comment by claremacrae** [comment]
I’m rather confused by these changes and would like to understand them. 

Please could you first describe the exact steps required by a user to reproduce any bugs that you are fixing. Many thanks.

**Comment by 1C0D** [comment]
indeed maybe having done several pushes. sry
except not using roll up and putting the main.ts in src
here is the final main.ts resulting file
```
import { Plugin, WorkspaceLeaf } from 'obsidian';
import { REVEAL_ACTIVE_FILE_BUTTON_ICON } from './constants';

export default class RevealActiveFileButtonPlugin extends Plugin {
	async onload() {
		// Initialize
		this.app.workspace.onLayoutReady(() => {
			const explorer = this.getFileExplorers();
			this.addRevealButton(explorer);
		});
		// File explorers that get opened later on
		this.registerEvent(
			this.app.workspace.on('layout-change', () => {
				const explorer = this.getFileExplorers();
				this.addRevealButton(explorer);
			})
		);
	}
	onunload() {
		// Remove all reveal buttons
		const explorer = this.getFileExplorers();
		this.removeRevealButton(explorer);
	}

	private addRevealButton(explorer: WorkspaceLeaf): void {
		const container = explorer.view.containerEl;
		const navContainer = container.querySelector(
			'div.nav-buttons-container'
		) as HTMLDivElement;

		const existingButton = this.getRevealButton(explorer);
		if (existingButton) {
			return;
		}

		const newIcon = navContainer.createEl(
			'button',
			{
				attr: { 'aria-label': 'Reveal active file' },
				cls: 'clickable-icon nav-action-button reveal-active-file-button'
			},
			(el) => {
				el.innerHTML = REVEAL_ACTIVE_FILE_BUTTON_ICON;
			}
		);
		this.registerDomEvent(newIcon, 'click', async () => {
			this.onButtonClick(explorer);
		});
	}

	/**
	 * Remove the reveal button from a given file explorer leaf.
	 */
	private removeRevealButton(explorer: WorkspaceLeaf): void {
		const button = this.getRevealButton(explorer);
		if (button) {
			button.remove();
		}
	}

	/**
	 * Reveal the active file in the given file explorer
	 */
	private onButtonClick = (explorer: WorkspaceLeaf) => {
		if (explorer) {
			// @ts-ignore
			await this.app.commands.executeCommandById(
				'file-explorer:reveal-active-file'
			);
		}
	}

	/**
	 * Returns all loaded file explorer leaf
	 */
	private getFileExplorers(): WorkspaceLeaf {
		return this.app.workspace.getLeavesOfType('file-explorer')[0];
	}

	/**
	 * Get the reveal button for a given file explorer, if it exists
	 */
	private getRevealButton(explorer: WorkspaceLeaf): HTMLDivElement | null {
		return explorer.view.containerEl.querySelector(
			'.reveal-active-file-button'
		);
	}
}
```

**Comment by 1C0D** [comment]
so the button has been created with createEl
and the called action is now used in a function called in an async function. because this action is a promise...
so this is not needed anymore to use a timer call the action twice

**Comment by 1C0D** [comment]
And about your question is it fixing a bug? not really. it's just a cleaner way to write some parts. If you don't push it won't change a lot. I thought it was really an interesting code so I understood it and changed part of code which can be improved to be clearer and more actual.

**Comment by claremacrae** [comment]
> so the button has been created with createEl
> and the called action is now used in a function called in an async function. because this action is a promise...
> so this is not needed anymore to use a timer to call the action twice

Aaaaahhhh. Right, thank you that explanation really helps. 

Very many thanks for your time on the code here, and to explain the reasons behind the code change. 

I would be happy to test out a new PR that just made the changes to the TypeScript code you have described (and not anything else like reformatting for example. I’m not saying there is any reformatting in this one, just that I can’t see any diffs so don’t know.)

Once I have had time to read through this PR I will close it though, as it is much, much too large in scope to be accepted.

It would take me several hours to review the changes and test them, not just because the diffs are not visible but because there are so many different types of changes. 

But again, I would love to accept a PR that only contains only the fixes needed to remove the double-click workaround cleanly.

**Comment by 1C0D** [comment]
No worry, in fact in a few lines I did another solution, clicking on the top title to reveal the file. Strangely, they did it for the folder at the same place, but not for the file. it is by far the more intuitive way to do it. Once you know it's there.

**Pull request closed without merging**
